COMMENT ON TABLE "tourism_regions" IS 'Haetteum 서비스에서 노출하는 광역 관광 지역';
COMMENT ON COLUMN "tourism_regions"."id" IS 'Haetteum 내부 관광 지역 식별자';
COMMENT ON COLUMN "tourism_regions"."slug" IS '웹과 API에서 사용하는 안정적인 영문 지역 식별자';
COMMENT ON COLUMN "tourism_regions"."name" IS '사용자에게 표시하는 지역명';
COMMENT ON COLUMN "tourism_regions"."provider_code" IS 'TourAPI 법정동 시도 코드';
COMMENT ON COLUMN "tourism_regions"."display_order" IS '메인 화면 지역 필터 표시 순서';
COMMENT ON COLUMN "tourism_regions"."is_active" IS '서비스에서 지역을 노출할지 여부';
COMMENT ON COLUMN "tourism_regions"."created_at" IS '내부 레코드 생성 시각';
COMMENT ON COLUMN "tourism_regions"."updated_at" IS '내부 레코드 최종 수정 시각';

COMMENT ON TABLE "tourism_districts" IS 'TourAPI 법정동 시군구 코드와 광역 관광 지역의 관계';
COMMENT ON COLUMN "tourism_districts"."id" IS 'Haetteum 내부 시군구 식별자';
COMMENT ON COLUMN "tourism_districts"."region_id" IS '소속 광역 관광 지역 식별자';
COMMENT ON COLUMN "tourism_districts"."provider_code" IS 'TourAPI 법정동 시군구 코드';
COMMENT ON COLUMN "tourism_districts"."name" IS '사용자에게 표시하는 시군구명';
COMMENT ON COLUMN "tourism_districts"."is_active" IS '서비스에서 시군구를 사용할지 여부';
COMMENT ON COLUMN "tourism_districts"."created_at" IS '내부 레코드 생성 시각';
COMMENT ON COLUMN "tourism_districts"."updated_at" IS '내부 레코드 최종 수정 시각';

COMMENT ON TABLE "places" IS 'TourAPI에서 동기화한 관광지 기본 정보';
COMMENT ON COLUMN "places"."id" IS 'Haetteum 내부 관광지 식별자';
COMMENT ON COLUMN "places"."source" IS '관광지 원본 provider 식별자';
COMMENT ON COLUMN "places"."external_id" IS 'provider가 부여한 관광지 식별자';
COMMENT ON COLUMN "places"."content_type_id" IS 'TourAPI 콘텐츠 타입 ID';
COMMENT ON COLUMN "places"."region_id" IS '소속 광역 관광 지역 식별자';
COMMENT ON COLUMN "places"."district_id" IS '소속 시군구 식별자이며 제공되지 않으면 NULL';
COMMENT ON COLUMN "places"."title" IS '관광지명';
COMMENT ON COLUMN "places"."address1" IS '기본 주소';
COMMENT ON COLUMN "places"."address2" IS '상세 주소';
COMMENT ON COLUMN "places"."zipcode" IS '우편번호';
COMMENT ON COLUMN "places"."longitude" IS 'WGS84 경도';
COMMENT ON COLUMN "places"."latitude" IS 'WGS84 위도';
COMMENT ON COLUMN "places"."map_level" IS 'TourAPI 지도 확대 레벨';
COMMENT ON COLUMN "places"."category1" IS 'TourAPI 신분류 대분류 코드';
COMMENT ON COLUMN "places"."category2" IS 'TourAPI 신분류 중분류 코드';
COMMENT ON COLUMN "places"."category3" IS 'TourAPI 신분류 소분류 코드';
COMMENT ON COLUMN "places"."telephone" IS '관광지 안내 전화번호';
COMMENT ON COLUMN "places"."homepage" IS '관광지 홈페이지 주소';
COMMENT ON COLUMN "places"."overview" IS '관광지 소개 설명';
COMMENT ON COLUMN "places"."primary_image_url" IS '대표 원본 이미지 URL';
COMMENT ON COLUMN "places"."primary_thumbnail_url" IS '대표 썸네일 이미지 URL';
COMMENT ON COLUMN "places"."image_copyright_type" IS '대표 이미지 공공누리 저작권 유형';
COMMENT ON COLUMN "places"."provider_created_at" IS 'provider 콘텐츠 최초 등록 시각';
COMMENT ON COLUMN "places"."provider_modified_at" IS 'provider 콘텐츠 최종 수정 시각';
COMMENT ON COLUMN "places"."is_visible" IS '서비스에서 관광지를 노출할지 여부';
COMMENT ON COLUMN "places"."last_synced_at" IS '내부 DB에 마지막으로 정상 반영한 시각';
COMMENT ON COLUMN "places"."created_at" IS '내부 레코드 생성 시각';
COMMENT ON COLUMN "places"."updated_at" IS '내부 레코드 최종 수정 시각';

COMMENT ON TABLE "tourism_sync_runs" IS '관광 데이터 전체 또는 증분 동기화 실행 이력';
COMMENT ON COLUMN "tourism_sync_runs"."id" IS '동기화 실행 식별자';
COMMENT ON COLUMN "tourism_sync_runs"."provider" IS '동기화 대상 관광 데이터 provider';
COMMENT ON COLUMN "tourism_sync_runs"."job_type" IS '전체 또는 증분 등 동기화 작업 유형';
COMMENT ON COLUMN "tourism_sync_runs"."status" IS '동기화 실행 상태';
COMMENT ON COLUMN "tourism_sync_runs"."requested_from" IS '증분 동기화 요청에 사용한 시작 기준 시각';
COMMENT ON COLUMN "tourism_sync_runs"."started_at" IS '동기화 실행 시작 시각';
COMMENT ON COLUMN "tourism_sync_runs"."finished_at" IS '동기화 실행 종료 시각';
COMMENT ON COLUMN "tourism_sync_runs"."fetched_count" IS '외부 provider에서 조회한 항목 수';
COMMENT ON COLUMN "tourism_sync_runs"."inserted_count" IS '새로 저장한 항목 수';
COMMENT ON COLUMN "tourism_sync_runs"."updated_count" IS '기존 값을 갱신한 항목 수';
COMMENT ON COLUMN "tourism_sync_runs"."deactivated_count" IS '비표출 상태로 전환한 항목 수';
COMMENT ON COLUMN "tourism_sync_runs"."failed_count" IS '처리에 실패한 항목 수';
COMMENT ON COLUMN "tourism_sync_runs"."error_summary" IS '비밀정보를 제외한 오류 요약';
