import type { NearbyPlaceResult } from "@/features/places/nearby-place-search-model";

export const nearbyPlaceSearchMock = [
  {
    id: "icheon-city-museum",
    title: "이천 시립박물관",
    category: "attraction",
    categoryLabel: "관광지",
    distanceKm: 3.1,
    travelMode: "car",
    travelMinutes: 8,
    description: "이천의 역사와 문화를 한눈에 볼 수 있는 박물관",
    rating: 4.6,
    reviewCount: 1_234,
    image: {
      src: "/images/themes/theme-culture-hanok.png",
      alt: "전통 건축과 문화 전시 공간",
    },
  },
  {
    id: "icheon-rice-breakfast",
    title: "임금님 쌀밥집",
    category: "restaurant",
    categoryLabel: "맛집",
    distanceKm: 0.8,
    travelMode: "car",
    travelMinutes: 3,
    description: "건강한 한정식과 이천 쌀밥이 맛있는 곳",
    rating: 4.8,
    reviewCount: 856,
    image: {
      src: "/images/themes/theme-food-cafe.png",
      alt: "정갈하게 차려진 이천 쌀밥 한상",
    },
  },
  {
    id: "cafe-oncheon",
    title: "카페 온천",
    category: "cafe",
    categoryLabel: "카페",
    distanceKm: 1.2,
    travelMode: "car",
    travelMinutes: 4,
    description: "온천을 테마로 한 편안한 감성 카페",
    rating: 4.5,
    reviewCount: 642,
    image: {
      src: "/images/places/icheon-termeden/restaurants/garden-cafe.png",
      alt: "정원 풍경을 바라보는 카페 테이블",
    },
  },
  {
    id: "termeden-resort",
    title: "테르메덴 리조트",
    category: "accommodation",
    categoryLabel: "숙소",
    distanceKm: 0.3,
    travelMode: "walk",
    travelMinutes: 5,
    description: "테르메덴과 연결된 편안한 휴식형 리조트",
    rating: 4.7,
    reviewCount: 312,
    image: {
      src: "/images/places/icheon-termeden/reviews/garden-spa.png",
      alt: "정원과 파빌리온이 보이는 이천 테르메덴 스파 풀",
    },
  },
  {
    id: "haeju-cold-noodles",
    title: "해주냉면",
    category: "restaurant",
    categoryLabel: "맛집",
    distanceKm: 2.3,
    travelMode: "car",
    travelMinutes: 7,
    description: "시원한 냉면으로 유명한 이천의 지역 맛집",
    rating: 4.4,
    reviewCount: 1_102,
    image: {
      src: "/images/festivals/icheon-rice-cultural-festival/food-experience.png",
      alt: "이천의 지역 식재료로 차린 저녁 식사",
    },
  },
  {
    id: "icheon-ceramic-village",
    title: "이천 도예마을",
    category: "attraction",
    categoryLabel: "관광지",
    distanceKm: 4.2,
    travelMode: "car",
    travelMinutes: 10,
    description: "도자기 공방과 전시를 함께 둘러보는 문화 공간",
    rating: 4.6,
    reviewCount: 528,
    image: {
      src: "/images/festivals/icheon-rice-cultural-festival/culture-stage.png",
      alt: "이천의 문화 체험 공간",
    },
  },
] as const satisfies readonly NearbyPlaceResult[];
